// ###################################
// ##### CANDLE PERCENTAGE RANGE #####
// ###################################

//@version=5
indicator("Candle Percentage Range", shorttitle="CPR", overlay=true)

// Input settings for visibility and color of each range category
show1  = input(true, "Show 1% Range")
show2  = input(true, "Show 2% Range")
show3  = input(true, "Show 3% Range")
show4  = input(true, "Show 4% Range")
show5  = input(true, "Show 5% Range")
show6  = input(true, "Show 6% Range")
show7  = input(true, "Show 7% Range")
show8  = input(true, "Show 8% Range")
show9  = input(true, "Show 9% Range")
show10 = input(true, "Show 10% Range")
show11 = input(true, "Show 11% Range")
show12 = input(true, "Show 12% Range")
show13 = input(true, "Show 13% Range")
show14 = input(true, "Show 14% Range")
show15 = input(true, "Show 15% Range")
show16 = input(true, "Show 16% Range")
show17 = input(true, "Show 17% Range")
show18 = input(true, "Show 18% Range")
show19 = input(true, "Show 19% Range")
show20 = input(true, "Show 20% Range")
show21 = input(true, "Show 21% Range")
show22 = input(true, "Show 22% Range")
show23 = input(true, "Show 23% Range")
show24 = input(true, "Show 24% Range")
show25 = input(true, "Show 25% Range")
show26 = input(true, "Show 26% Range")
show27 = input(true, "Show 27% Range")
show28 = input(true, "Show 28% Range")
show29 = input(true, "Show 29% Range")
show30 = input(true, "Show 30% Range")
show31 = input(true, "Show 31% Range")
show32 = input(true, "Show 32% Range")
show33 = input(true, "Show 33% Range")
show34 = input(true, "Show 34% Range")
show35 = input(true, "Show 35% Range")
show36 = input(true, "Show 36% Range")
show37 = input(true, "Show 37% Range")
show38 = input(true, "Show 38% Range")
show39 = input(true, "Show 39% Range")
show40 = input(true, "Show 40% Range")
show41 = input(true, "Show 41% Range")
show42 = input(true, "Show 42% Range")
show43 = input(true, "Show 43% Range")
show44 = input(true, "Show 44% Range")
show45 = input(true, "Show 45% Range")
show46 = input(true, "Show 46% Range")
show47 = input(true, "Show 47% Range")
show48 = input(true, "Show 48% Range")
show49 = input(true, "Show 49% Range")
show50 = input(true, "Show 50% Range")
show51 = input(true, "Show 51% Range")
show52 = input(true, "Show 52% Range")
show53 = input(true, "Show 53% Range")
show54 = input(true, "Show 54% Range")
show55 = input(true, "Show 55% Range")
show56 = input(true, "Show 56% Range")
show57 = input(true, "Show 57% Range")
show58 = input(true, "Show 58% Range")
show59 = input(true, "Show 59% Range")
show60 = input(true, "Show 60% Range")
show61 = input(true, "Show 61% Range")
show62 = input(true, "Show 62% Range")
show63 = input(true, "Show 63% Range")
show64 = input(true, "Show 64% Range")
show65 = input(true, "Show 65% Range")
show66 = input(true, "Show 66% Range")
show67 = input(true, "Show 67% Range")
show68 = input(true, "Show 68% Range")
show69 = input(true, "Show 69% Range")
show70 = input(true, "Show 70% Range")
show71 = input(true, "Show 71% Range")
show72 = input(true, "Show 72% Range")
show73 = input(true, "Show 73% Range")
show74 = input(true, "Show 74% Range")
show75 = input(true, "Show 75% Range")
show76 = input(true, "Show 76% Range")
show77 = input(true, "Show 77% Range")
show78 = input(true, "Show 78% Range")
show79 = input(true, "Show 79% Range")
show80 = input(true, "Show 80% Range")
show81 = input(true, "Show 81% Range")
show82 = input(true, "Show 82% Range")
show83 = input(true, "Show 83% Range")
show84 = input(true, "Show 84% Range")
show85 = input(true, "Show 85% Range")
show86 = input(true, "Show 86% Range")
show87 = input(true, "Show 87% Range")
show88 = input(true, "Show 88% Range")
show89 = input(true, "Show 89% Range")
show90 = input(true, "Show 90% Range")
show91 = input(true, "Show 91% Range")
show92 = input(true, "Show 92% Range")
show93 = input(true, "Show 93% Range")
show94 = input(true, "Show 94% Range")
show95 = input(true, "Show 95% Range")
show96 = input(true, "Show 96% Range")
show97 = input(true, "Show 97% Range")
show98 = input(true, "Show 98% Range")
show99 = input(true, "Show 99% Range")
show100 = input(true, "Show 100% Range")
show100plus = input(true, "Show 100+% Range")

// Additional input for label text color
labelTextColor = input(color.white, "Label Text Color")

// Function to calculate the percentage range of a candle
candleRangePct() =>
    candleRange = (high - low) / close * 100
    candleRange
    
// Function to calculate the absolute range of a candle
candleAbsoluteRange() =>
    high - low


// Function to determine the label text and color based on the range
getLabelParams(candleRange) =>
    var color labelColor = na // Explicit type declaration for labelColor
    labelText = ""
 
	if candleRange >= 1    and candleRange < 2    and show1
		labelText := "1"
	else if candleRange >= 2    and candleRange < 3    and show2
		labelText := "2"
	else if candleRange >= 3    and candleRange < 4    and show3
		labelText := "3"
	else if candleRange >= 4    and candleRange < 5    and show4
		labelText := "4"
	else if candleRange >= 5    and candleRange < 6    and show5
		labelText := "5"
	else if candleRange >= 6    and candleRange < 7    and show6
		labelText := "6"
	else if candleRange >= 7    and candleRange < 8    and show7
		labelText := "7"
	else if candleRange >= 8    and candleRange < 9    and show8
		labelText := "8"
	else if candleRange >= 9    and candleRange < 10   and show9
		labelText := "9"
	else if candleRange >= 10   and candleRange < 11   and show10
		labelText := "10"
	else if candleRange >= 11   and candleRange < 12   and show11
		labelText := "11"
	else if candleRange >= 12   and candleRange < 13   and show12
		labelText := "12"
	else if candleRange >= 13   and candleRange < 14   and show13
		labelText := "13"
	else if candleRange >= 14   and candleRange < 15   and show14
		labelText := "14"
	else if candleRange >= 15   and candleRange < 16   and show15
		labelText := "15"
	else if candleRange >= 16   and candleRange < 17   and show16
		labelText := "16"
	else if candleRange >= 17   and candleRange < 18   and show17
		labelText := "17"
	else if candleRange >= 18   and candleRange < 19   and show18
		labelText := "18"
	else if candleRange >= 19   and candleRange < 20   and show19
		labelText := "19"
	else if candleRange >= 20   and candleRange < 21   and show20
		labelText := "20"
	else if candleRange >= 21   and candleRange < 22   and show21
		labelText := "21"
	else if candleRange >= 22   and candleRange < 23   and show22
		labelText := "22"
	else if candleRange >= 23   and candleRange < 24   and show23
		labelText := "23"
	else if candleRange >= 24   and candleRange < 25   and show24
		labelText := "24"
	else if candleRange >= 25   and candleRange < 26   and show25
		labelText := "25"
	else if candleRange >= 26   and candleRange < 27   and show26
		labelText := "26"
	else if candleRange >= 27   and candleRange < 28   and show27
		labelText := "27"
	else if candleRange >= 28   and candleRange < 29   and show28
		labelText := "28"
	else if candleRange >= 29   and candleRange < 30   and show29
		labelText := "29"
	else if candleRange >= 30   and candleRange < 31   and show30
		labelText := "30"
	else if candleRange >= 31   and candleRange < 32   and show31
		labelText := "31"
	else if candleRange >= 32   and candleRange < 33   and show32
		labelText := "32"
	else if candleRange >= 33   and candleRange < 34   and show33
		labelText := "33"
	else if candleRange >= 34   and candleRange < 35   and show34
		labelText := "34"
	else if candleRange >= 35   and candleRange < 36   and show35
		labelText := "35"
	else if candleRange >= 36   and candleRange < 37   and show36
		labelText := "36"
	else if candleRange >= 37   and candleRange < 38   and show37
		labelText := "37"
	else if candleRange >= 38   and candleRange < 39   and show38
		labelText := "38"
	else if candleRange >= 39   and candleRange < 40   and show39
		labelText := "39"
	else if candleRange >= 40   and candleRange < 41   and show40
		labelText := "40"
	else if candleRange >= 41   and candleRange < 42   and show41
		labelText := "41"
	else if candleRange >= 42   and candleRange < 43   and show42
		labelText := "42"
	else if candleRange >= 43   and candleRange < 44   and show43
		labelText := "43"
	else if candleRange >= 44   and candleRange < 45   and show44
		labelText := "44"
	else if candleRange >= 45   and candleRange < 46   and show45
		labelText := "45"
	else if candleRange >= 46   and candleRange < 47   and show46
		labelText := "46"
	else if candleRange >= 47   and candleRange < 48   and show47
		labelText := "47"
	else if candleRange >= 48   and candleRange < 49   and show48
		labelText := "48"
	else if candleRange >= 49   and candleRange < 50   and show49
		labelText := "49"
	else if candleRange >= 50   and candleRange < 51   and show50
		labelText := "50"
	else if candleRange >= 51   and candleRange < 52   and show51
		labelText := "51"
	else if candleRange >= 52   and candleRange < 53   and show52
		labelText := "52"
	else if candleRange >= 53   and candleRange < 54   and show53
		labelText := "53"
	else if candleRange >= 54   and candleRange < 55   and show54
		labelText := "54"
	else if candleRange >= 55   and candleRange < 56   and show55
		labelText := "55"
	else if candleRange >= 56   and candleRange < 57   and show56
		labelText := "56"
	else if candleRange >= 57   and candleRange < 58   and show57
		labelText := "57"
	else if candleRange >= 58   and candleRange < 59   and show58
		labelText := "58"
	else if candleRange >= 59   and candleRange < 60   and show59
		labelText := "59"
	else if candleRange >= 60   and candleRange < 61   and show60
		labelText := "60"
	else if candleRange >= 61   and candleRange < 62   and show61
		labelText := "61"
	else if candleRange >= 62   and candleRange < 63   and show62
		labelText := "62"
	else if candleRange >= 63   and candleRange < 64   and show63
		labelText := "63"
	else if candleRange >= 64   and candleRange < 65   and show64
		labelText := "64"
	else if candleRange >= 65   and candleRange < 66   and show65
		labelText := "65"
	else if candleRange >= 66   and candleRange < 67   and show66
		labelText := "66"
	else if candleRange >= 67   and candleRange < 68   and show67
		labelText := "67"
	else if candleRange >= 68   and candleRange < 69   and show68
		labelText := "68"
	else if candleRange >= 69   and candleRange < 70   and show69
		labelText := "69"
	else if candleRange >= 70   and candleRange < 71   and show70
		labelText := "70"
	else if candleRange >= 71   and candleRange < 72   and show71
		labelText := "71"
	else if candleRange >= 72   and candleRange < 73   and show72
		labelText := "72"
	else if candleRange >= 73   and candleRange < 74   and show73
		labelText := "73"
	else if candleRange >= 74   and candleRange < 75   and show74
		labelText := "74"
	else if candleRange >= 75   and candleRange < 76   and show75
		labelText := "75"
	else if candleRange >= 76   and candleRange < 77   and show76
		labelText := "76"
	else if candleRange >= 77   and candleRange < 78   and show77
		labelText := "77"
	else if candleRange >= 78   and candleRange < 79   and show78
		labelText := "78"
	else if candleRange >= 79   and candleRange < 80   and show79
		labelText := "79"
	else if candleRange >= 80   and candleRange < 81   and show80
		labelText := "80"
	else if candleRange >= 81   and candleRange < 82   and show81
		labelText := "81"
	else if candleRange >= 82   and candleRange < 83   and show82
		labelText := "82"
	else if candleRange >= 83   and candleRange < 84   and show83
		labelText := "83"
	else if candleRange >= 84   and candleRange < 85   and show84
		labelText := "84"
	else if candleRange >= 85   and candleRange < 86   and show85
		labelText := "85"
	else if candleRange >= 86   and candleRange < 87   and show86
		labelText := "86"
	else if candleRange >= 87   and candleRange < 88   and show87
		labelText := "87"
	else if candleRange >= 88   and candleRange < 89   and show88
		labelText := "88"
	else if candleRange >= 89   and candleRange < 90   and show89
		labelText := "89"
	else if candleRange >= 90   and candleRange < 91   and show90
		labelText := "90"
	else if candleRange >= 91   and candleRange < 92   and show91
		labelText := "91"
	else if candleRange >= 92   and candleRange < 93   and show92
		labelText := "92"
	else if candleRange >= 93   and candleRange < 94   and show93
		labelText := "93"
	else if candleRange >= 94   and candleRange < 95   and show94
		labelText := "94"
	else if candleRange >= 95   and candleRange < 96   and show95
		labelText := "95"
	else if candleRange >= 96   and candleRange < 97   and show96
		labelText := "96"
	else if candleRange >= 97   and candleRange < 98   and show97
		labelText := "97"
	else if candleRange >= 98   and candleRange < 99   and show98
		labelText := "98"
	else if candleRange >= 99   and candleRange < 100  and show99
		labelText := "99"
	else if candleRange >= 100  and candleRange < 101  and show100
		labelText := "100"
	else if candleRange >= 101  and candleRange < 100000 and show100plus
		labelText := "100+"

    [labelText, labelColor]

// Main logic for labeling each candle
rangePct = candleRangePct()
[labelText, labelColor] = getLabelParams(rangePct)
if labelText != ""
    label.new(bar_index, high, text=labelText, color=labelColor, style=label.style_none, textcolor=labelTextColor, yloc=yloc.belowbar, size=size.small)
